import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryProvider } from "@/provider/reactQueryProvidor";
import { I18nProvider } from "@/provider/I18nProvider";
import { Toaster } from "sonner";

const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-my-font",
});

export const metadata: Metadata = {
  title: "Zony Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <I18nProvider>
          <ReactQueryProvider>
            <Toaster position="top-center" richColors />
            {children}
          </ReactQueryProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
